# nazwa workflow
name: Run tests

# push, pullrequest, workflowdispatch
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: repo

      - uses: actions/setup-python@v5
        name: python
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: ruff check .

  # job
  test:
    name: Perform tests
    needs: lint
    runs-on: ubuntu-latest

    steps:
      # checkout repo
      - uses: actions/checkout@v4
        name: repo 

      #instalka pythona
      - uses: actions/setup-python@v5
        name: install python
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: pytest -q
